name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v2.3.1
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: 'gradle'
    - name: Build with Gradle
      run: ./gradlew clean build

