name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Java JDK
      uses: actions/setup-java@v2.3.1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew clean build

